TE5-T269 Swift Basic
buddhdev-jay/IOS_DEMO pull request #2
Opened 2022-01-13 11:57 UTC by buddhdev-jay

2022-01-17 03:35 UTC, purvesh-d commented on Swift_Basic.playground/Contents.swift
> +
Remove extra empty lines

2022-01-17 03:37 UTC, purvesh-d requested changes
Please resolve comment.

2022-01-19 04:04 UTC, purvesh-d requested changes
- Resovle all comments
- There should be single commit in single PR.

2022-01-19 04:04 UTC, purvesh-d commented on Swift_Basic.playground/Contents.swift
> +
Remove extra empty lines from here as well from all the files which are included in this PR.

2022-01-19 04:04 UTC, purvesh-d commented on Swift_Basic.playground/Contents.swift
> +}while num1<5
Code formating required. Try select all code and then Ctrl+ i to formate it.

2022-01-19 04:04 UTC, purvesh-d commented on Swift_Exercise.playground/Contents.swift
> +//2.Write a Swift program to create a new string without the first and last character of a given string
Why this commented code added ?

2022-01-19 04:06 UTC, buddhdev-jay commented on Swift_Basic.playground/Contents.swift
> +
okk

2022-01-21 12:13 UTC, purvesh-d requested changes

2022-01-21 12:13 UTC, purvesh-d commented on Swift_Exercise.playground/Contents.swift
> +if array1.count > 2{
Code formatting

2022-01-21 12:42 UTC, merged