TE5-T519 Webview Implemented
buddhdev-jay/IOS_DEMO pull request #5
Opened 2022-03-14 05:27 UTC by buddhdev-jay

2022-03-16 06:23 UTC, purvesh-d requested changes

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +        return 2
static integer

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +        print("you tapped")
use debugPrint instead of consol print

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +        print("you tapped")
use debugPrint instead of consol print

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +            {
code formatting

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +            {
code formatting

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageControlViewController.swift
> +        case 0:
static integer, you can take enum

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageControlViewController.swift
> +        case 0:
static integer, you can take enum

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +                guard previousIndex >= 0 else {return nil}
static integer, check in all the files

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +                guard previousIndex >= 0 else {return nil}
static integer, check in all the files

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/ScrollViewController.swift
> +    // MARK: -  View Lifecycle
add empty line before mark

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/ScrollViewController.swift
> +    // MARK: -  View Lifecycle
add empty line before mark

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +    var timer: Timer?
need mark for variables and move it after outlets

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +    var timer: Timer?
need mark for variables and move it after outlets

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +    // MARK: -  View Lifecycle
add empty line

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +    // MARK: -  View Lifecycle
add empty line

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +        {
code formatting

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +        {
code formatting

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/ViewController.swift
>      override func viewDidLoad() {
need mark for view life cycle

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/ViewController.swift
>      override func viewDidLoad() {
need mark for view life cycle

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/WebviewViewController.swift
> +                loadUrl(urlString!)
remove force casting

2022-03-16 06:23 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/WebviewViewController.swift
> +                loadUrl(urlString!)
remove force casting

2022-03-21 06:00 UTC, purvesh-d requested changes

2022-03-23 03:41 UTC, purvesh-d requested changes

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewCell.swift
> +            backgroundColor = .gray
You can write this in ternary operator with single line

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +        if section == Constants.ZERO {
You can use ternary operator instead of if else

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +        if section == Constants.ZERO {
You can use ternary operator instead of if else

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +            cell.tableCelllbl?.text = names[indexPath.row]
why you are setting text here ? even if you have created configCell func

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +            cell.tableCelllbl?.text = names[indexPath.row]
why you are setting text here ? even if you have created configCell func

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +
extra empty line

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/TableViewController/TableViewController.swift
> +
extra empty line

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UICollectionView/CollectionViewController.swift
> +        if section == Constants.ZERO {
use ternary

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UICollectionView/CollectionViewController.swift
> +        if section == Constants.ZERO {
use ternary

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +              if let vc = vcList.first{
1. code formatting
2. proper naming of variables

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +              if let vc = vcList.first{
1. code formatting
2. proper naming of variables

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +                guard previousIndex < vcList.count else {return nil}
make these 3 guard let into single

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +                guard previousIndex < vcList.count else {return nil}
make these 3 guard let into single

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +                guard previousIndex < vcList.count else {return nil}
same here

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/PageViewController.swift
> +                guard previousIndex < vcList.count else {return nil}
same here

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/ScrollViewController.swift
> +        let TableViewVc = self.storyboard?.instantiateViewController(withIdentifier: Constants.tableViewVc) as! TableViewController
force casting ` as! TableViewController`

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/ScrollViewController.swift
> +        let TableViewVc = self.storyboard?.instantiateViewController(withIdentifier: Constants.tableViewVc) as! TableViewController
force casting ` as! TableViewController`

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/ScrollViewController.swift
> +        let SignupScreenVc = self.storyboard?.instantiateViewController(withIdentifier: Constants.signupScreenVc) as! Signup_Screen_ViewController
1. same ` as! Signup_Screen_ViewController`
2.  ViewController name should be in camel case with first letter capital

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/ScrollViewController.swift
> +        let SignupScreenVc = self.storyboard?.instantiateViewController(withIdentifier: Constants.signupScreenVc) as! Signup_Screen_ViewController
1. same ` as! Signup_Screen_ViewController`
2.  ViewController name should be in camel case with first letter capital

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +            lblGender.text = Constants.genderMale
use ternary

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +            lblGender.text = Constants.genderMale
use ternary

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +            let change: Float = 0.1
static float

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/Signup_Screen_ViewController.swift
> +            let change: Float = 0.1
static float

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/UISegmentedViewController.swift
> +        case 0:
static integer

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/UISegmentedViewController.swift
> +        case 0:
static integer

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/WebviewViewController.swift
> +                loadUrl("http://\(urlString)")
Why you have appended `http:` ?

2022-03-23 03:41 UTC, purvesh-d commented on IOS_DEMO/IOS_DEMO/UIComponents/WebviewViewController.swift
> +                loadUrl("http://\(urlString)")
Why you have appended `http:` ?

2022-03-24 06:16 UTC, buddhdev-jay commented on IOS_DEMO/IOS_DEMO/UIComponents/WebviewViewController.swift
> +                loadUrl("http://\(urlString)")
if user directly put google.com so we need to append https://

2022-03-25 04:28 UTC, purvesh-d approved these changes

2022-03-25 04:28 UTC, merged